- name: Ubuntu - Get some useful things from the package manager
  when: ansible_distribution == 'Ubuntu'
  apt:
    state: present
    name: 
      - curl
      - git
      - python3-dev
      - postgresql 
      - postgresql-contrib
      - libpq-dev

- name: Amazon - Get some useful things from the package manager
  when: ansible_distribution == 'Amazon'
  yum:
    state: present
    name:
    - curl
    - git
    - python3-devel
    - postgresql

- name: pip
  pip:
    state: present
    name: 
      - pipenv
      - awscli

# So that your VM time stays correct
- name: Ubuntu - Ensure time sync
  when: ansible_distribution == 'Ubuntu'
  service:
    name: systemd-timesyncd
    state: started

- name: Amazon - Ensure time sync
  when: ansible_distribution == 'Amazon'
  service:
    name: chronyd
    state: started
